// <auto-generated />
using System;
using Asseta.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Asseta.Infrastructure.Migrations
{
    [DbContext(typeof(AssetaDbContext))]
    partial class AssetaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Asseta.Domain.Entities.ActionCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedTrustedPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_trusted_person_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("ContinuityItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("continuity_item_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DigitalStorageLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("digital_storage_link");

                    b.Property<string>("DocumentLocationHint")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("document_location_hint");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("urgency_stage");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContinuityItemId")
                        .IsUnique()
                        .HasDatabaseName("idx_action_cards_continuity_item");

                    b.HasIndex("Urgency")
                        .HasDatabaseName("idx_action_cards_urgency");

                    b.HasIndex("OwnerId", "IsDeleted")
                        .HasDatabaseName("idx_action_cards_owner_deleted");

                    b.HasIndex("OwnerId", "Urgency", "IsDeleted")
                        .HasDatabaseName("idx_action_cards_owner_urgency_deleted");

                    b.ToTable("action_cards", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ActionCardContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActionCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_card_id");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactNotes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_notes");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RelationshipOrRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("relationship_or_role");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActionCardId")
                        .HasDatabaseName("idx_action_card_contacts_card");

                    b.ToTable("action_card_contacts", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ActionCardStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActionCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_card_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EstimatedDuration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estimated_duration");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("instruction");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActionCardId", "StepOrder")
                        .HasDatabaseName("idx_action_card_steps_card_order");

                    b.ToTable("action_card_steps", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ActionCardTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultPriority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_priority");

                    b.Property<string>("DefaultUrgency")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("default_urgency");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("SuggestedRolesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_roles");

                    b.Property<string>("SuggestedStepsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_steps");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("template_code");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title_vi");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TemplateCode")
                        .IsUnique();

                    b.ToTable("action_card_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CategoryCode = "FINANCIAL",
                            CreatedAtUtc = new DateTime(2026, 9, 5, 16, 24, 24, 181, DateTimeKind.Utc).AddTicks(9014),
                            DefaultPriority = "CRITICAL",
                            DefaultUrgency = "FIRST_72_HOURS",
                            IsDeleted = false,
                            SuggestedRolesJson = "[\"Cán bộ tín dụng ngân hàng\",\"Kế toán phụ trách\",\"Người đồng bảo lãnh\"]",
                            SuggestedStepsJson = "[{\"stepOrder\":1,\"instruction\":\"Liên hệ cán bộ tín dụng phụ trách khoản vay để đối soát lịch trả nợ\",\"estimatedDuration\":\"30 phút\"},{\"stepOrder\":2,\"instruction\":\"Kiểm tra hợp đồng tín dụng và khế ước nhận nợ gốc trong tủ tài liệu\",\"estimatedDuration\":\"15 phút\"},{\"stepOrder\":3,\"instruction\":\"Đảm bảo tài khoản thanh toán tự động có đủ số dư cho kỳ trích nợ kế tiếp\",\"estimatedDuration\":\"20 phút\"}]",
                            TemplateCode = "TPL_BANK_LOAN",
                            TitleEn = "Handle Bank Loan & Debt Obligations",
                            TitleVi = "Xử lý Khoản vay & Nghĩa vụ Trả nợ Ngân hàng"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            CategoryCode = "PROPERTY",
                            CreatedAtUtc = new DateTime(2026, 9, 5, 16, 24, 24, 181, DateTimeKind.Utc).AddTicks(9056),
                            DefaultPriority = "IMPORTANT",
                            DefaultUrgency = "FIRST_7_DAYS",
                            IsDeleted = false,
                            SuggestedRolesJson = "[\"Người thuê nhà\",\"Ban quản lý tòa nhà\",\"Môi giới quản lý\"]",
                            SuggestedStepsJson = "[{\"stepOrder\":1,\"instruction\":\"Thông báo cho người thuê về đầu mối liên hệ tiếp nhận tiền thuê\",\"estimatedDuration\":\"15 phút\"},{\"stepOrder\":2,\"instruction\":\"Kiểm tra hợp đồng thuê và hóa đơn phí quản lý/dịch vụ của tòa nhà\",\"estimatedDuration\":\"30 phút\"},{\"stepOrder\":3,\"instruction\":\"Lưu giữ biên lai thanh toán định kỳ vào hồ sơ bất động sản\",\"estimatedDuration\":\"10 phút\"}]",
                            TemplateCode = "TPL_RENTAL_PROPERTY",
                            TitleEn = "Manage Rental Property & Tenants",
                            TitleVi = "Quản lý Bất động sản Cho thuê & Khách thuê"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            CategoryCode = "INSURANCE",
                            CreatedAtUtc = new DateTime(2026, 9, 5, 16, 24, 24, 181, DateTimeKind.Utc).AddTicks(9060),
                            DefaultPriority = "CRITICAL",
                            DefaultUrgency = "IMMEDIATE",
                            IsDeleted = false,
                            SuggestedRolesJson = "[\"Đại lý bảo hiểm phục vụ\",\"Tổng đài bồi thường\",\"Bác sĩ điều trị\"]",
                            SuggestedStepsJson = "[{\"stepOrder\":1,\"instruction\":\"Gọi hotline công ty bảo hiểm thông báo sự kiện bảo hiểm\",\"estimatedDuration\":\"20 phút\"},{\"stepOrder\":2,\"instruction\":\"Tìm giấy chứng nhận bảo hiểm nhân thọ và phụ lục hợp đồng\",\"estimatedDuration\":\"15 phút\"},{\"stepOrder\":3,\"instruction\":\"Thu thập hồ sơ bệnh án hoặc giấy tờ xác nhận y tế từ bệnh viện\",\"estimatedDuration\":\"1-2 ngày\"}]",
                            TemplateCode = "TPL_LIFE_INSURANCE",
                            TitleEn = "Claim Insurance Benefits & Coverage",
                            TitleVi = "Yêu cầu Quyền lợi Bồi thường Bảo hiểm"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            CategoryCode = "BUSINESS",
                            CreatedAtUtc = new DateTime(2026, 9, 5, 16, 24, 24, 181, DateTimeKind.Utc).AddTicks(9092),
                            DefaultPriority = "CRITICAL",
                            DefaultUrgency = "IMMEDIATE",
                            IsDeleted = false,
                            SuggestedRolesJson = "[\"Đồng sáng lập (Co-founder)\",\"Kế toán trưởng\",\"Luật sư doanh nghiệp\"]",
                            SuggestedStepsJson = "[{\"stepOrder\":1,\"instruction\":\"Họp khẩn ban lãnh đạo/đồng sáng lập kích hoạt quy trình ủy quyền\",\"estimatedDuration\":\"1 giờ\"},{\"stepOrder\":2,\"instruction\":\"Thông báo nhân sự chủ chốt duy trì hoạt động kinh doanh thường nhật\",\"estimatedDuration\":\"30 phút\"},{\"stepOrder\":3,\"instruction\":\"Kiểm tra các lệnh chi lương và nghĩa vụ thanh toán nhà cung cấp\",\"estimatedDuration\":\"45 phút\"}]",
                            TemplateCode = "TPL_BUSINESS_OPS",
                            TitleEn = "Emergency Business Operations & Power of Attorney",
                            TitleVi = "Ủy quyền Điều hành Khẩn cấp & Vận hành Doanh nghiệp"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            CategoryCode = "DOCUMENTS",
                            CreatedAtUtc = new DateTime(2026, 9, 5, 16, 24, 24, 181, DateTimeKind.Utc).AddTicks(9097),
                            DefaultPriority = "IMPORTANT",
                            DefaultUrgency = "FIRST_72_HOURS",
                            IsDeleted = false,
                            SuggestedRolesJson = "[\"Người giữ chìa khóa phụ\",\"Luật sư riêng\"]",
                            SuggestedStepsJson = "[{\"stepOrder\":1,\"instruction\":\"Tìm chìa khóa hoặc vị trí cất giữ tủ hồ sơ bảo mật\",\"estimatedDuration\":\"15 phút\"},{\"stepOrder\":2,\"instruction\":\"Kiểm tra danh mục sổ đỏ, giấy khai sinh, đăng ký kết hôn, giấy phép ĐKKD\",\"estimatedDuration\":\"30 phút\"},{\"stepOrder\":3,\"instruction\":\"Chụp lưu bản sao số hóa và niêm phong lại tài liệu gốc\",\"estimatedDuration\":\"20 phút\"}]",
                            TemplateCode = "TPL_LEGAL_DOCS",
                            TitleEn = "Access Vital Legal Documents & Contracts",
                            TitleVi = "Tiếp cận Tủ Hồ sơ Pháp lý & Hợp đồng Cốt tử"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            CategoryCode = "FAMILY",
                            CreatedAtUtc = new DateTime(2026, 9, 5, 16, 24, 24, 181, DateTimeKind.Utc).AddTicks(9101),
                            DefaultPriority = "IMPORTANT",
                            DefaultUrgency = "FIRST_7_DAYS",
                            IsDeleted = false,
                            SuggestedRolesJson = "[\"Người giám hộ tạm thời\",\"Giáo viên chủ nhiệm\",\"Bác sĩ gia đình\"]",
                            SuggestedStepsJson = "[{\"stepOrder\":1,\"instruction\":\"Kiểm tra hạn nộp học phí của con hoặc viện phí người cao tuổi\",\"estimatedDuration\":\"20 phút\"},{\"stepOrder\":2,\"instruction\":\"Thiết lập người phụ trách đưa đón và chăm sóc sinh hoạt hàng ngày\",\"estimatedDuration\":\"30 phút\"}]",
                            TemplateCode = "TPL_FAMILY_SUPPORT",
                            TitleEn = "Maintain Family Support & Dependent Obligations",
                            TitleVi = "Duy trì Nghĩa vụ & Chi phí Người phụ thuộc"
                        });
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ActivationConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("activation_request_id");

                    b.Property<DateTime>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmed");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("TrustedPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("trusted_person_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ActivationRequestId", "TrustedPersonId")
                        .IsUnique();

                    b.ToTable("activation_confirmations", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ActivationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GracePeriodExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("grace_period_expires_at_utc");

                    b.Property<Guid?>("InitiatedByTrustedPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by_trusted_person_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger_source");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Status");

                    b.ToTable("activation_requests", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ContinuityAssessmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssessmentVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("v1")
                        .HasColumnName("assessment_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("InitialReadinessScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("initial_readiness_score");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("ItemsGeneratedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("items_generated_count");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("RawResponses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_responses");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CreatedAtUtc")
                        .HasDatabaseName("idx_continuity_assessment_history_owner");

                    b.ToTable("continuity_assessment_history", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ContinuityAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PayloadSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_snapshot");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CreatedAtUtc")
                        .HasDatabaseName("idx_continuity_audit_logs_owner_time");

                    b.ToTable("continuity_audit_logs", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ContinuityCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_vi");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("continuity_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("018e6e5a-7341-789a-9e12-2d93e1104e01"),
                            Code = "FINANCIAL",
                            CreatedAtUtc = new DateTime(2026, 9, 5, 16, 24, 24, 183, DateTimeKind.Utc).AddTicks(7003),
                            Icon = "wallet",
                            IsDeleted = false,
                            NameEn = "Financial & Monetary Obligations",
                            NameVi = "Tài chính & Nghĩa vụ tiền tệ",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("018e6e5a-7341-789a-9e12-2d93e1104e02"),
                            Code = "PROPERTY",
                            CreatedAtUtc = new DateTime(2026, 9, 5, 16, 24, 24, 183, DateTimeKind.Utc).AddTicks(7009),
                            Icon = "home",
                            IsDeleted = false,
                            NameEn = "Property & Real Estate",
                            NameVi = "Tài sản & Bất động sản",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("018e6e5a-7341-789a-9e12-2d93e1104e03"),
                            Code = "INSURANCE",
                            CreatedAtUtc = new DateTime(2026, 9, 5, 16, 24, 24, 183, DateTimeKind.Utc).AddTicks(7013),
                            Icon = "shield",
                            IsDeleted = false,
                            NameEn = "Insurance & Health Policies",
                            NameVi = "Bảo hiểm & Quyền lợi sức khỏe",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("018e6e5a-7341-789a-9e12-2d93e1104e04"),
                            Code = "BUSINESS",
                            CreatedAtUtc = new DateTime(2026, 9, 5, 16, 24, 24, 183, DateTimeKind.Utc).AddTicks(7017),
                            Icon = "briefcase",
                            IsDeleted = false,
                            NameEn = "Business Operations & Partners",
                            NameVi = "Doanh nghiệp & Quan hệ đối tác",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("018e6e5a-7341-789a-9e12-2d93e1104e05"),
                            Code = "DOCUMENTS",
                            CreatedAtUtc = new DateTime(2026, 9, 5, 16, 24, 24, 183, DateTimeKind.Utc).AddTicks(7021),
                            Icon = "file-text",
                            IsDeleted = false,
                            NameEn = "Legal Documents & Records",
                            NameVi = "Hồ sơ & Giấy tờ pháp lý",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("018e6e5a-7341-789a-9e12-2d93e1104e06"),
                            Code = "FAMILY",
                            CreatedAtUtc = new DateTime(2026, 9, 5, 16, 24, 24, 183, DateTimeKind.Utc).AddTicks(7035),
                            Icon = "users",
                            IsDeleted = false,
                            NameEn = "Family & Personal Obligations",
                            NameVi = "Gia đình & Nghĩa vụ cá nhân",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ContinuityItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActionCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_card_id");

                    b.Property<Guid?>("AssignedTrustedPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_trusted_person_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CipherAuthTag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cipher_auth_tag");

                    b.Property<string>("CipherNonce")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cipher_nonce");

                    b.Property<string>("CipherNotesBlob")
                        .HasColumnType("text")
                        .HasColumnName("cipher_notes_blob");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentLocationHint")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("document_location_hint");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("row_version");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActionCardId")
                        .HasDatabaseName("idx_continuity_items_action_card");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_continuity_items_category");

                    b.HasIndex("OwnerId", "IsDeleted")
                        .HasDatabaseName("idx_continuity_items_owner_deleted");

                    b.ToTable("continuity_items", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.OwnerActivationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CheckInIntervalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("check_in_interval_days");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GracePeriodHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(48)
                        .HasColumnName("grace_period_hours");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastCheckInAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_check_in_at_utc");

                    b.Property<int>("MinConfirmationsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("min_confirmations_required");

                    b.Property<DateTime>("NextCheckInDueUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_check_in_due_utc");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.HasIndex("NextCheckInDueUtc", "Status");

                    b.ToTable("owner_activation_configs", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.TrustedPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DelegateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("delegate_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("relationship");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("role_description");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TrustLevel")
                        .HasColumnType("integer")
                        .HasColumnName("trust_level");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "IsDeleted");

                    b.ToTable("trusted_people", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.TrustedPersonPairingCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_until");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("salt");

                    b.Property<Guid>("TrustedPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("trusted_person_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id");

                    b.HasIndex("TrustedPersonId", "IsUsed", "ExpiresAt");

                    b.ToTable("trusted_person_pairing_codes", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.TrustedPersonPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean")
                        .HasColumnName("can_view");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("permission_type");

                    b.Property<Guid?>("TargetActionCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_action_card_id");

                    b.Property<Guid?>("TargetCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_category_id");

                    b.Property<Guid>("TrustedPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("trusted_person_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TargetActionCardId");

                    b.HasIndex("TargetCategoryId");

                    b.HasIndex("TrustedPersonId", "TargetActionCardId");

                    b.HasIndex("TrustedPersonId", "TargetCategoryId");

                    b.ToTable("trusted_person_permissions", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EncryptionSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("encryption_salt");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("MasterKeyVerifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("master_key_verifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("user_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ActionCard", b =>
                {
                    b.HasOne("Asseta.Domain.Entities.ContinuityCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Asseta.Domain.Entities.ContinuityItem", "ContinuityItem")
                        .WithOne()
                        .HasForeignKey("Asseta.Domain.Entities.ActionCard", "ContinuityItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Asseta.Domain.ValueObjects.CipherBlobPayload", "CipherInstructions", b1 =>
                        {
                            b1.Property<Guid>("ActionCardId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AuthTag")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("cipher_auth_tag");

                            b1.Property<string>("CipherBlob")
                                .HasColumnType("text")
                                .HasColumnName("cipher_instructions_blob");

                            b1.Property<string>("Nonce")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("cipher_nonce");

                            b1.HasKey("ActionCardId");

                            b1.ToTable("action_cards");

                            b1.WithOwner()
                                .HasForeignKey("ActionCardId");
                        });

                    b.Navigation("Category");

                    b.Navigation("CipherInstructions");

                    b.Navigation("ContinuityItem");
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ActionCardContact", b =>
                {
                    b.HasOne("Asseta.Domain.Entities.ActionCard", "ActionCard")
                        .WithMany("Contacts")
                        .HasForeignKey("ActionCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionCard");
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ActionCardStep", b =>
                {
                    b.HasOne("Asseta.Domain.Entities.ActionCard", "ActionCard")
                        .WithMany("Steps")
                        .HasForeignKey("ActionCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionCard");
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ActivationConfirmation", b =>
                {
                    b.HasOne("Asseta.Domain.Entities.ActivationRequest", null)
                        .WithMany("Confirmations")
                        .HasForeignKey("ActivationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ContinuityItem", b =>
                {
                    b.HasOne("Asseta.Domain.Entities.ContinuityCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Asseta.Domain.Entities.TrustedPersonPairingCode", b =>
                {
                    b.HasOne("Asseta.Domain.Entities.TrustedPerson", "TrustedPerson")
                        .WithMany("PairingCodes")
                        .HasForeignKey("TrustedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrustedPerson");
                });

            modelBuilder.Entity("Asseta.Domain.Entities.TrustedPersonPermission", b =>
                {
                    b.HasOne("Asseta.Domain.Entities.ActionCard", "TargetActionCard")
                        .WithMany()
                        .HasForeignKey("TargetActionCardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Asseta.Domain.Entities.ContinuityCategory", "TargetCategory")
                        .WithMany()
                        .HasForeignKey("TargetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Asseta.Domain.Entities.TrustedPerson", "TrustedPerson")
                        .WithMany("Permissions")
                        .HasForeignKey("TrustedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetActionCard");

                    b.Navigation("TargetCategory");

                    b.Navigation("TrustedPerson");
                });

            modelBuilder.Entity("Asseta.Domain.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("Asseta.Domain.Entities.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ActionCard", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ActivationRequest", b =>
                {
                    b.Navigation("Confirmations");
                });

            modelBuilder.Entity("Asseta.Domain.Entities.ContinuityCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Asseta.Domain.Entities.TrustedPerson", b =>
                {
                    b.Navigation("PairingCodes");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Asseta.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
